// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh3ZWi3gUZSI9uslRcUV9oFUNEpIlf560',
    appId: '1:238647026188:web:c18d8da07925e9d3624429',
    messagingSenderId: '238647026188',
    projectId: 'eshannotes',
    authDomain: 'eshannotes.firebaseapp.com',
    storageBucket: 'eshannotes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3AlO6UTVPqPs3BuB4zvziaeDhAXOiWwU',
    appId: '1:238647026188:android:ca8ccc77d2a28961624429',
    messagingSenderId: '238647026188',
    projectId: 'eshannotes',
    storageBucket: 'eshannotes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6XWqYzBhhZmTuYU1ZdArjT-x5mRn-lbY',
    appId: '1:238647026188:ios:42b0cfc7d6e3bf63624429',
    messagingSenderId: '238647026188',
    projectId: 'eshannotes',
    storageBucket: 'eshannotes.appspot.com',
    iosBundleId: 'com.examplessssssssss.notes',
  );
}
